### ISSUE TITLE
Create UML - Use cases

### ISSUE THREAD

**Issue by levtmadden** [OrientDN-InternalProjects/2023SEInternSS1-book-store-api#1]
Create use cases diagram

**Comment by justme2002** [comment]
Hi @levtmadden 
Please Take a look at our Use - Case Diagram
Thank you

![Image](https://user-images.githubusercontent.com/77768060/219268526-291970ce-075e-4df9-b5ee-2e3d22a6368e.png)

**Comment by levtmadden** [comment]
please use verbs for the use cases diagram. [*] management is not valid for me though

**Comment by justme2002** [comment]
Hi, we have updated by changing the typo from Noun (Management) to Verb (Verb) in some use-cases. Look for your review
thank you.

![Image](https://user-images.githubusercontent.com/77768060/219285832-69539aff-ce1e-4d9b-bbcc-e58caeac26c4.png)

**Comment by justme2002** [comment]
Hi, we have updated our use cases diagram by separating this diagram into specific parts
Please notice that download the diagram file on https://drive.google.com/file/d/1tJwNzXunbQ9k7ZAt-wEvw0J_CYDzrAhD/view?usp=sharing and at the navigation bar of this HTML file by navigating to page 3 / 4 to view the diagram

thank you for reviewing.
