### ISSUE TITLE
Create UML - Class diagram

### ISSUE THREAD

**Issue by levtmadden** [OrientDN-InternalProjects/2023SEInternSS1-book-store-api#4]

**Comment by Dat070601** [comment]
Dear @levtmadden 

Please take a look at our Class Diagram.

Thank you

![Image](https://user-images.githubusercontent.com/80233722/219269347-5e21ceaa-6e7f-44cd-b5ab-eda04c66f0cd.png)

**Comment by justme2002** [comment]
Hi, we have updated by adding some missing details (Methods) to this diagram
Please notice that download the diagram file on https://drive.google.com/file/d/1tJwNzXunbQ9k7ZAt-wEvw0J_CYDzrAhD/view?usp=sharing and at the navigation bar of this HTML file by navigating to page 2 / 4 to view the diagram

thank you for reviewing.
