### ISSUE TITLE
Create UML - Sequence diagram

### ISSUE THREAD

**Issue by levtmadden** [OrientDN-InternalProjects/2023SEInternSS1-book-store-api#5]

**Comment by justme2002** [comment]
Hi, we have finished the sequence diagram.
Please notice that download the diagram file on https://drive.google.com/file/d/1tJwNzXunbQ9k7ZAt-wEvw0J_CYDzrAhD/view?usp=sharing and at the navigation bar of this HTML file by navigating to page 4 / 4 to view the diagram

thank you for reviewing.
